accelerator:            gpu     # cpu or gpu
devices:                1       # Number of GPU nodes for distributed training.
num_nodes:              1       # Number of devices to train on (int), which devices to train on (list or str), or "auto".

max_epochs:             2000 # 1000     # Stop training once this number of epochs is reached.
freeze_encoder_params:  False  # If encoder parameters should be freezed or not.

dataset_name:           ImageNet   # Dataset to use. Can be: ImageNet, Imagenette, MNIST, GTSRB, ...
train_batch_size:       64 # 256
val_batch_size:         6
check_val_every_n_epoch: 25

criterion_to_use:       "kyles_version" # Criterion to use. Can be 'kendall_and_gal', 'kyles_version' or 'softmax_only'
num_mc_sims:            100      #  Number of Monte Carlo Simulations to run if bayesian approach is used.
augment_data:           False    # Set if test time data augmentation should be performed. Can be true or false.
num_data_augmentations: 128      # Number of data augmentation to create and use in test time augmentation. Paper used 128 for predictions
rotation_and_flip:      False

dataset_root_path: "~/datasets"  # defines with dataset root path to use. Cluster: "~/datasets", Local: "/mnt/HDD1/datasets"