accelerator:            cpu     # cpu or gpu
devices:                1       # Number of GPU nodes for distributed training.
num_nodes:              1       # Number of devices to train on (int), which devices to train on (list or str), or "auto".

max_epochs:             500     # Stop training once this number of epochs is reached.
freeze_encoder_params:  True    # If encoder parameters should be freezed or not.

dataset_name:           Imagenette  # Dataset to use. Can be: Imagenet, Imagenette, MNIST, GTSRB, ...
batch_size:             40
criterion_to_use:       softmax_only # Criterion to use. Can be 'kendall_and_gal', 'kyles_version' or 'softmax_only'
num_mc_sims:            100      #  Number of Monte Carlo Simulations to run if bayesian approach is used.
augment_data:           True     # Set if test time data augmentation should be performed. Can be true or false.
num_data_augmentations: 128      # Number of data augmentation to create and use in test time augmentation. Paper used 128 for predictions